### ISSUE TITLE
Link to deeplearn.js is broken

### ISSUE THREAD

**Issue by alblaine** [PAIR-code/pair-code.github.io#2]
Links to https://pair-code.github.io/deeplearnjs/ are resulting in a 404 error.

**Comment by jameswex** [comment]
Thanks for bringing this to our attention. We will fix it to ensure that https://pair-code.github.io/deeplearnjs/ correctly redirects to deeplearnjs.org (the new page for deeplearn.js)

**Comment by jameswex** [comment]
The links on https://pair-code.github.io/ have been updated to point to deeplearnjs.org and the page https://pair-code.github.io/deeplearnjs/ will soon redirect appropriately. I'll close this bug.
