### ISSUE TITLE
What-if-tool

### ISSUE THREAD

**Issue by Mahund** [PAIR-code/pair-code.github.io#3]
Hello!
I only want to ask how did you link your github [page](https://pair-code.github.io/) to the what-if-tool [page](https://pair-code.github.io/what-if-tool/).
Thanks!

**Comment by jameswex** [comment]
Our pair-code.github.io page (for the pair-code github organization) redirects to https://ai.google/research/teams/brain/pair. The What-If Tool page (https://pair-code.github.io/what-if-tool/) is served through github pages using the website code on the master branch of that repository (https://github.com/pair-code/what-if-tool)
